version: '3.6'

services:
  backend:
    build: 
      context: ./docker/backend
      args:
        USER_ID: ${USER_ID:-1000}
        GROUP_ID: ${GROUP_ID:-1000}
    volumes: 
      - ./backend:/django
      - ./docker/backend/docker-entrypoint.sh:/bin/docker-entrypoint.sh
    env_file: .env
    environment:
      - USER_ID=${USER_ID:-1000}
      - GROUP_ID=${GROUP_ID:-1000}
    expose:
      - 8000
    restart: unless-stopped
    command: /bin/docker-entrypoint.sh
    user: django
    depends_on:
      - postgres
      - solr

  nginx:
    image: nginx:1.17.9
    volumes:
      - ./backend:/django
      - ./frontend/public:/frontend
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
      - ./docker/nginx/.logs:/var/log/nginx
    env_file: .env
    ports:
      - ${NGINX_HTTP_PORT:-80}:80
    restart: unless-stopped
    depends_on:
      - backend

  postgres:
    image: postgres:12.2
    volumes:
      - ./docker/postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - ./docker/postgres/.data:/var/lib/postgresql/data
    env_file: .env
    expose:
      - 5432
    restart: unless-stopped

  solr:
    image: solr:8.5.1
    volumes:
      - ./docker/solr/judge:/var/solr/data/judge
      - ./docker/solr/doj.json:/tmp/doj.json
    command:
      - solr-precreate
      - gettingstarted
    expose:
      - 8983
